export const ActionTypes ={

    FETCH_PRODUCTS:'FETCH_PRODUCTS',
    SET_PRODUCTS:'SET_PRODUCTS',
    REMOVE_SELECTED_PRODUCT:'REMOVE_SELECTED_PRODUCT',
    SET_PRODUCT:'SET_PRODUCT',
    SET_CATEGORIES:'SET_CATEGORIES',

    ADD_CART:'ADD_CART',
    UPDATE_CART:'UPDATE_CART',
    GET_NUMBER_CART:'GET_NUMBER_CART',
    DECREASE_QUANTITY:'DECREASE_QUANTITY',
    INCREASE_QUANTITY:'INCREASE_QUANTITY',
    DELETE_CART:'DELETE_CART',
    

}